addons: 
  apt: 
    packages: 
      - llvm-8
      - clang-8
      - cmake
    sources: 
      - 
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
        sourceline: "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
dist: xenial
language: 
  - cpp
os: 
  - linux
script: 
  - "bash test"
