#!/bin/bash

set -x

mkdir -p _build
pushd _build
cmake ..
make -j4
popd
$CC -g -S -emit-llvm -o test.bc test.cpp
$OPT $1 -instnamer -p -load _build/*/*LLVMIRPlusPlus* -llvmir++  -debug-only=llvmir++ test.bc > /dev/null
rm -rf _build # test.bc
